In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
melb_data = pd.read_csv("melb_data.csv")

In [6]:
melb_data.describe()

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,18396.000000,18396.000000,1.839600e+04,18395.000000,18395.000000,14927.000000,14925.000000,14820.000000,13603.000000,7762.000000,8958.000000,15064.000000,15064.000000,18395.000000
mean,11826.787073,2.935040,1.056697e+06,10.389986,3107.140147,2.913043,1.538492,1.615520,558.116371,151.220219,1965.879996,-37.809849,144.996338,7517.975265
std,6800.710448,0.958202,6.419217e+05,6.009050,95.000995,0.964641,0.689311,0.955916,3987.326586,519.188596,37.013261,0.081152,0.106375,4488.416599
min,1.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,5936.750000,2.000000,6.330000e+05,6.300000,3046.000000,2.000000,1.000000,1.000000,176.500000,93.000000,1950.000000,-37.858100,144.931193,4294.000000
50%,11820.500000,3.000000,8.800000e+05,9.700000,3085.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.803625,145.000920,6567.000000
75%,17734.250000,3.000000,1.302000e+06,13.300000,3149.000000,3.000000,2.000000,2.000000,651.000000,174.000000,2000.000000,-37.756270,145.060000,10331.000000
max,23546.000000,12.000000,9.000000e+06,48.100000,3978.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [7]:
melb_data.head(10)

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
5,10,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,7/05/2016,2.5,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.8041,144.9953,Northern Metropolitan,4019.0
6,11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019.0
7,14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.8060,144.9954,Northern Metropolitan,4019.0
8,15,Abbotsford,217 Langridge St,3,h,1000000.0,S,Jellis,8/10/2016,2.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
9,16,Abbotsford,18a Mollison St,2,t,745000.0,S,Jellis,8/10/2016,2.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0

In [8]:
melb_data.columns

Index(['Unnamed: 0', 'Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method',
       'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea',
       'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [9]:
Y = melb_data['Price']

In [10]:
Y

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
5         941000.0
6        1876000.0
7        1636000.0
8        1000000.0
9         745000.0
10        300000.0
11       1097000.0
12        542000.0
13        760000.0
14        481000.0
15        700000.0
16       1350000.0
17        750000.0
18       1985000.0
19        500000.0
20       1172500.0
21        441000.0
22       1310000.0
23       1200000.0
24        847000.0
25       1176500.0
26        955000.0
27        890000.0
28       1330000.0
29        900000.0
           ...
18366     720000.0
18367     631000.0
18368     523000.0
18369     530000.0
18370     540000.0
18371     290000.0
18372    1263500.0
18373     931000.0
18374    1295000.0
18375    1250000.0
18376    1316000.0
18377     951000.0
18378    1323000.0
18379     970000.0
18380    1330000.0
18381     590000.0
18382     650000.0
18383     540000.0
18384     635000.0
18385     655000.0
18386     582000.0
18387     720000.0
18388    1245000.0
18389    1031000.0
18390    1170000.0
18391     622500.0
18392    2500000.0
18393    1100000.0
18394    1285000.0
18395    1050000.0
Name: Price, Length: 18396, dtype: float64

In [11]:
melb_data.dtypes

Unnamed: 0         int64
Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [12]:
X = melb_data.select_dtypes(exclude=["object"]).dropna(axis=0)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X.shape

(6830, 14)

In [15]:
Y.shape

(18396,)

In [16]:
%config IPCompleter.greedy=True

In [17]:
melb_data.Price

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
5         941000.0
6        1876000.0
7        1636000.0
8        1000000.0
9         745000.0
10        300000.0
11       1097000.0
12        542000.0
13        760000.0
14        481000.0
15        700000.0
16       1350000.0
17        750000.0
18       1985000.0
19        500000.0
20       1172500.0
21        441000.0
22       1310000.0
23       1200000.0
24        847000.0
25       1176500.0
26        955000.0
27        890000.0
28       1330000.0
29        900000.0
           ...
18366     720000.0
18367     631000.0
18368     523000.0
18369     530000.0
18370     540000.0
18371     290000.0
18372    1263500.0
18373     931000.0
18374    1295000.0
18375    1250000.0
18376    1316000.0
18377     951000.0
18378    1323000.0
18379     970000.0
18380    1330000.0
18381     590000.0
18382     650000.0
18383     540000.0
18384     635000.0
18385     655000.0
18386     582000.0
18387     720000.0
18388    1245000.0
18389    1031000.0
18390    1170000.0
18391     622500.0
18392    2500000.0
18393    1100000.0
18394    1285000.0
18395    1050000.0
Name: Price, Length: 18396, dtype: float64

In [18]:
melb_data.Address

0               85 Turner St
1            25 Bloomburg St
2               5 Charles St
3           40 Federation La
4                55a Park St
5             129 Charles St
6               124 Yarra St
7              98 Charles St
8           217 Langridge St
9            18a Mollison St
10        6/241 Nicholson St
11             10 Valiant St
12       403/609 Victoria St
13         25/84 Trenerry Cr
14         106/119 Turner St
15        411/8 Grosvenor St
16           40 Nicholson St
17       123/56 Nicholson St
18                22 Park St
19         13/84 Trenerry Cr
20             45 William St
21        7/20 Abbotsford St
22             16 William St
23               42 Henry St
24          250 Langridge St
25               78 Yarra St
26          196 Nicholson St
27             42 Valiant St
28           3/72 Charles St
29        13/11 Nicholson St
                ...
18366     21/1059 Malvern Rd
18367       25/637 Orrong Rd
18368           12 Arthur Cl
18369        3/32 Banksia Gr
18370           7 Londrew Ct
18371         1/34 Sharps Rd
18372         73 Nurlendi Rd
18373        308 Hawthorn Rd
18374          2 Settlers Ct
18375          9 Winswood Cl
18376          149 Graham Rd
18377     16 chesterfield Ct
18378           12 Armagh Cr
18379          34 Fewster Dr
18380             15 Mara Cl
18381         2/14 Daours Ct
18382          76 Kenmare St
18383           91 Latham St
18384            5 Nuragi Ct
18385        1/21 Waratah St
18386             9 Black St
18387        81 Hillcrest Dr
18388           12 Strada Cr
18389          77 Merrett Dr
18390            83 Power St
18391        8/2 Thompson St
18392           96 Verdon St
18393           17 Amaroo Wy
18394             6 Agnes St
18395          33 Freeman St
Name: Address, Length: 18396, dtype: object

In [19]:
X

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
1,2,2,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,-37.80790,144.99340,4019.0
2,4,3,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,-37.80930,144.99440,4019.0
4,6,4,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,-37.80720,144.99410,4019.0
6,11,3,1876000.0,2.5,3067.0,4.0,2.0,0.0,245.0,210.0,1910.0,-37.80240,144.99930,4019.0
7,14,2,1636000.0,2.5,3067.0,2.0,1.0,2.0,256.0,107.0,1890.0,-37.80600,144.99540,4019.0
11,18,2,1097000.0,2.5,3067.0,3.0,1.0,2.0,220.0,75.0,1900.0,-37.80100,144.99890,4019.0
16,24,3,1350000.0,2.5,3067.0,3.0,2.0,2.0,214.0,190.0,2005.0,-37.80850,144.99640,4019.0
17,25,2,750000.0,2.5,3067.0,2.0,2.0,1.0,0.0,94.0,2009.0,-37.80780,144.99650,4019.0
22,30,2,1310000.0,2.5,3067.0,2.0,1.0,2.0,238.0,97.0,1890.0,-37.80900,144.99760,4019.0
23,32,3,1200000.0,2.5,3067.0,3.0,2.0,1.0,113.0,110.0,1880.0,-37.80560,144.99300,4019.0
25,35,3,1176500.0,2.5,3067.0,2.0,1.0,1.0,138.0,105.0,1890.0,-37.80210,144.99650,4019.0
27,37,2,890000.0,2.5,3067.0,2.0,1.0,1.0,150.0,73.0,1985.0,-37.80110,145.00040,4019.0
28,38,4,1330000.0,2.5,3067.0,4.0,2.0,2.0,780.0,135.0,1900.0,-37.80730,144.99520,4019.0
31,42,2,500000.0,2.5,3067.0,2.0,1.0,1.0,0.0,60.0,1970.0,-37.80150,144.99720,4019.0
32,43,2,1100000.0,2.5,3067.0,2.0,2.0,1.0,124.0,135.0,2013.0,-37.80790,144.99770,4019.0
33,44,2,1315000.0,2.5,3067.0,2.0,1.0,0.0,147.0,85.0,1900.0,-37.80800,144.99400,4019.0
37,49,3,1447500.0,2.5,3067.0,3.0,3.0,1.0,166.0,174.0,2012.0,-37.80170,145.00010,4019.0
39,51,2,1135000.0,2.5,3067.0,2.0,2.0,2.0,98.0,128.0,1920.0,-37.80050,144.99520,4019.0
44,56,3,1290000.0,2.5,3067.0,3.0,1.0,1.0,168.0,124.0,1950.0,-37.80070,144.99580,4019.0
45,57,1,470000.0,2.5,3067.0,1.0,1.0,1.0,0.0,50.0,2013.0,-37.80550,144.99610,4019.0
46,58,2,1180000.0,2.5,3067.0,2.0,1.0,0.0,162.0,91.0,1900.0,-37.80160,144.99560,4019.0
47,59,3,1195000.0,2.5,3067.0,3.0,2.0,1.0,120.0,128.0,1998.0,-37.80220,144.99540,4019.0
48,61,2,1012500.0,2.5,3067.0,2.0,1.0,0.0,182.0,82.0,1900.0,-37.80210,144.99760,4019.0
50,63,2,1030000.0,2.5,3067.0,2.0,1.0,1.0,172.0,81.0,1930.0,-37.80860,144.99460,4019.0
52,66,3,840000.0,13.5,3042.0,3.0,2.0,1.0,303.0,225.0,2016.0,-37.71800,144.87800,3464.0
53,67,3,730000.0,13.5,3042.0,3.0,2.0,1.0,0.0,145.0,1965.0,-37.72030,144.87550,3464.0
54,68,3,770000.0,13.5,3042.0,3.0,2.0,1.0,0.0,145.0,1965.0,-37.72030,144.87550,3464.0
55,70,2,603000.0,13.5,3042.0,2.0,1.0,1.0,272.0,84.0,1950.0,-37.72940,144.88800,3464.0
56,71,3,700000.0,13.5,3042.0,3.0,2.0,2.0,239.0,134.0,2009.0,-37.72180,144.88370,3464.0
57,72,3,600000.0,13.5,3042.0,2.0,1.0,1.0,290.0,116.0,1980.0,-37.72730,144.87440,3464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18266,23387,3,910000.0,8.4,3072.0,3.0,1.0,2.0,276.0,96.0,1965.0,-37.75277,145.00734,14577.0
18272,23394,3,640000.0,12.0,3073.0,3.0,1.0,1.0,224.0,128.0,2008.0,-37.71289,145.01967,21650.0
18273,23395,4,1112000.0,12.0,3073.0,4.0,2.0,10.0,1002.0,170.0,1985.0,-37.70671,145.03086,21650.0
18277,23400,4,852000.0,12.0,3073.0,4.0,3.0,2.0,527.0,240.0,1980.0,-37.69968,145.03426,21650.0
18278,23401,3,800000.0,12.0,3073.0,3.0,1.0,2.0,585.0,90.0,1960.0,-37.73173,145.02884,21650.0
18279,23402,2,625500.0,12.0,3073.0,2.0,1.0,2.0,343.0,111.0,1960.0,-37.71626,144.99866,21650.0
18284,23410,3,700000.0,19.9,3134.0,3.0,2.0,2.0,605.0,126.0,1977.0,-37.81010,145.21697,7785.0
18286,23413,2,937000.0,21.3,3135.0,2.0,2.0,2.0,736.0,116.0,1960.0,-37.80401,145.25225,4407.0
18289,23416,3,1224000.0,8.9,3084.0,3.0,1.0,2.0,609.0,124.0,1960.0,-37.74351,145.07965,3540.0
18292,23419,4,621000.0,20.6,3064.0,4.0,2.0,2.0,574.0,202.0,1997.0,-37.63499,144.93409,5833.0
18295,23422,4,1490000.0,15.2,3191.0,4.0,2.0,2.0,503.0,168.0,1930.0,-37.95685,145.01977,4497.0
18297,23425,3,890000.0,22.2,3179.0,3.0,1.0,2.0,724.0,116.0,1980.0,-37.88953,145.22056,2206.0
18299,23427,3,512000.0,35.4,3198.0,3.0,1.0,1.0,576.0,105.0,1983.0,-38.10505,145.15328,8077.0
18303,23431,4,1502000.0,5.1,3011.0,4.0,3.0,1.0,934.0,199.0,2014.0,-37.80898,144.88701,2417.0
18318,23452,4,537000.0,14.0,3021.0,4.0,2.0,2.0,447.0,134.0,1996.0,-37.75405,144.82014,14042.0
18327,23461,3,1848000.0,8.2,3041.0,3.0,1.0,3.0,824.0,189.0,1935.0,-37.73797,144.92455,3284.0
18332,23467,3,605000.0,31.7,3429.0,3.0,2.0,2.0,755.0,229.0,1996.0,-37.56533,144.71233,14092.0
18333,23468,3,717500.0,10.5,3020.0,3.0,1.0,1.0,554.0,95.0,1985.0,-37.78514,144.84561,3755.0
18341,23476,3,1715000.0,10.2,3127.0,3.0,1.0,2.0,438.0,151.0,1906.0,-37.83015,145.09035,5457.0
18346,23482,3,350000.0,18.4,3029.0,3.0,1.0,1.0,466.0,103.0,2003.0,-37.86744,144.65609,10160.0
18355,23492,5,1400000.0,12.4,3107.0,5.0,3.0,2.0,717.0,310.0,1963.0,-37.76630,145.11320,5420.0
18364,23501,3,1271000.0,7.0,3071.0,3.0,1.0,2.0,470.0,151.0,1950.0,-37.75937,145.01534,8870.0
18370,23512,3,540000.0,12.9,3043.0,3.0,1.0,1.0,607.0,102.0,1970.0,-37.69423,144.88002,3296.0
18377,23521,4,951000.0,14.7,3152.0,4.0,2.0,2.0,704.0,200.0,1981.0,-37.85639,145.23536,5424.0
18380,23525,4,1330000.0,14.7,3152.0,4.0,2.0,2.0,717.0,191.0,1980.0,-37.86887,145.22116,7082.0
18382,23527,2,650000.0,14.5,3087.0,2.0,1.0,1.0,210.0,79.0,2006.0,-37.70657,145.07878,2329.0
18384,23532,4,635000.0,14.7,3030.0,4.0,2.0,1.0,662.0,172.0,1980.0,-37.89327,144.64789,16166.0
18389,23538,3,1031000.0,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,-37.85927,144.87904,6380.0
18392,23541,4,2500000.0,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,-37.85908,144.89299,6380.0
18394,23545,4,1285000.0,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,-37.81188,144.88449,6543.0

In [20]:
melb_data.shape

(18396, 22)

In [21]:
X.shape

(6830, 14)

In [22]:
melb_data.Price.shape

(18396,)

In [23]:
X = melb_data.select_dtypes(exclude=["object"])

In [25]:
X.shape

(18396, 14)

In [27]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [28]:
X.columns

Index(['Unnamed: 0', 'Rooms', 'Price', 'Distance', 'Postcode', 'Bedroom2',
       'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude',
       'Longtitude', 'Propertycount'],
      dtype='object')

In [30]:
X = X.drop(["Price"], axis=1)

In [31]:
X.columns

Index(['Unnamed: 0', 'Rooms', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude',
       'Longtitude', 'Propertycount'],
      dtype='object')

In [32]:
X.shape

(18396, 13)

In [33]:
X.dtypes

Unnamed: 0         int64
Rooms              int64
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
Lattitude        float64
Longtitude       float64
Propertycount    float64
dtype: object

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, melb_data.Price, random_state=0)

In [35]:
X_train.shape

(13797, 13)

In [36]:
model = RandomForestRegressor(n_estimators=10, max_depth=40)

In [38]:
X_train.isnull().sum()

Unnamed: 0          0
Rooms               0
Distance            1
Postcode            1
Bedroom2         2594
Bathroom         2595
Car              2671
Landsize         3576
BuildingArea     7986
YearBuilt        7064
Lattitude        2499
Longtitude       2499
Propertycount       1
dtype: int64

In [41]:
X = pd.get_dummies(melb_data.dropna(axis=0))

In [42]:
X.isnull().sum()

Unnamed: 0                               0
Rooms                                    0
Price                                    0
Distance                                 0
Postcode                                 0
Bedroom2                                 0
Bathroom                                 0
Car                                      0
Landsize                                 0
BuildingArea                             0
YearBuilt                                0
Lattitude                                0
Longtitude                               0
Propertycount                            0
Suburb_Abbotsford                        0
Suburb_Aberfeldie                        0
Suburb_Airport West                      0
Suburb_Albanvale                         0
Suburb_Albert Park                       0
Suburb_Albion                            0
Suburb_Alphington                        0
Suburb_Altona                            0
Suburb_Altona Meadows                    0
Suburb_Altona North                      0
Suburb_Ardeer                            0
Suburb_Armadale                          0
Suburb_Ascot Vale                        0
Suburb_Ashburton                         0
Suburb_Ashwood                           0
Suburb_Aspendale                         0
                                        ..
CouncilArea_Greater Dandenong            0
CouncilArea_Hobsons Bay                  0
CouncilArea_Hume                         0
CouncilArea_Kingston                     0
CouncilArea_Knox                         0
CouncilArea_Macedon Ranges               0
CouncilArea_Manningham                   0
CouncilArea_Maribyrnong                  0
CouncilArea_Maroondah                    0
CouncilArea_Melbourne                    0
CouncilArea_Melton                       0
CouncilArea_Monash                       0
CouncilArea_Moonee Valley                0
CouncilArea_Moreland                     0
CouncilArea_Nillumbik                    0
CouncilArea_Port Phillip                 0
CouncilArea_Stonnington                  0
CouncilArea_Whitehorse                   0
CouncilArea_Whittlesea                   0
CouncilArea_Wyndham                      0
CouncilArea_Yarra                        0
CouncilArea_Yarra Ranges                 0
Regionname_Eastern Metropolitan          0
Regionname_Eastern Victoria              0
Regionname_Northern Metropolitan         0
Regionname_Northern Victoria             0
Regionname_South-Eastern Metropolitan    0
Regionname_Southern Metropolitan         0
Regionname_Western Metropolitan          0
Regionname_Western Victoria              0
Length: 6719, dtype: int64

In [43]:
X.shape

(6196, 6719)

In [46]:
y = X.Price

In [47]:
y

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
11       1097000.0
16       1350000.0
17        750000.0
22       1310000.0
23       1200000.0
25       1176500.0
27        890000.0
28       1330000.0
31        500000.0
32       1100000.0
33       1315000.0
37       1447500.0
39       1135000.0
44       1290000.0
45        470000.0
46       1180000.0
47       1195000.0
48       1012500.0
50       1030000.0
52        840000.0
53        730000.0
54        770000.0
55        603000.0
56        700000.0
57        600000.0
           ...
15333     880000.0
15335     945000.0
15336     730000.0
15338     980000.0
15345     570000.0
15350     600000.0
15351     360000.0
15353     475000.0
15354     495000.0
15356     695000.0
15357     760000.0
15358     583500.0
15360     585000.0
15363    1245000.0
15364    2000000.0
15366     407000.0
15369     891000.0
15370     615500.0
15371     300000.0
15375    1310000.0
15380     645000.0
15381     482500.0
15382     394000.0
15385     821000.0
15386     635000.0
15388     601000.0
15389    1050000.0
15390     385000.0
15392     560000.0
15395    2450000.0
Name: Price, Length: 6196, dtype: float64

In [48]:
X.columns

Index(['Unnamed: 0', 'Rooms', 'Price', 'Distance', 'Postcode', 'Bedroom2',
       'Bathroom', 'Car', 'Landsize', 'BuildingArea',
       ...
       'CouncilArea_Yarra', 'CouncilArea_Yarra Ranges',
       'Regionname_Eastern Metropolitan', 'Regionname_Eastern Victoria',
       'Regionname_Northern Metropolitan', 'Regionname_Northern Victoria',
       'Regionname_South-Eastern Metropolitan',
       'Regionname_Southern Metropolitan', 'Regionname_Western Metropolitan',
       'Regionname_Western Victoria'],
      dtype='object', length=6719)

In [51]:
X = X.drop(["Price"], axis=1)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [53]:
model.fit(X_train, y_train).score(X_test, y_test)

0.7278687492281406

In [1]:
from PIL import Image
import numpy as np
i = Image.open("download.jpeg")
a  = np.asarray(i)
a.shape

(159, 318, 3)

In [4]:
i = Image.open("download (1) 16-33-01-694.jpeg")
a = np.asarray(i)
a.shape

(40, 40, 3)

In [5]:
i = Image.open("18813218.jpeg")
a = np.asarray(i)
a.shape

(180, 240, 3)

In [6]:
new = i.convert('1')
new.save("djfaldf.jpeg")

In [7]:
a_new = np.asarray(new)

In [8]:
a_new.shape

(180, 240)

In [9]:
old = i.convert('RGB')

In [11]:
old.save("od.jpeg")

In [12]:
old_arr = np.asarray(old)
old_arr.shape

(180, 240, 3)

In [1]:
old.save("od.jpeg")

NameError: name 'old' is not defined